[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
merkle_airdrop = "c1yG6B2Ch8SWuwKmAToWK8oKiUkPVeVhVLNgAEoSDTs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "deploy-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
